# This is a basic workflow to help you get started with Actions

name: Update Geodata auto

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Run download_data.sh
        run: cd db/ && bash download_data.sh

      - name: Check Git Status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Git仓库有以下更改："
            git status
            echo "changes=yes" >> $GITHUB_ENV
          else
            echo "Git仓库没有未提交的更改，跳过后续步骤。"
            echo "changes=no" >> $GITHUB_ENV
          fi

      - name: Run v2unpack
        if: env.changes == 'yes'
        run: bash v2unpack.sh

      - name: Git Push
        if: env.changes == 'yes'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout --orphan latest_branch
          git add -A
          git commit -am "$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")"
          git branch -D master
          git branch -m master
          git push -f "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" master

      # test
      - name: Install rename
        if: env.changes == 'yes'
        run: sudo apt-get update && sudo apt-get install -y rename

      - name: Git push assets to mosdns branch
        if: env.changes == 'yes'
        run: |
          cd original/
          rename 's/geosite_//' geosite/*
          rename 's/geoip_//' geoip/*
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b mosdns
          git add .
          git commit -m "$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")"
          git push -f "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" mosdns

      - name: Git push assets to mihomo branch
        if: env.changes == 'yes'
        run: |
          cd rule-set/
          rename 's/geosite_//' geosite/*
          rename 's/geoip_//' geoip/*
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b mihomo
          git add .
          git commit -m "$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")"
          git push -f "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" mihomo

      - name: Git push assets to sing-box branch
        if: env.changes == 'yes'
        run: |
          cd sing-box/
          rename 's/geosite-//' geosite/*
          rename 's/geoip-//' geoip/*
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b sing-box
          git add .
          git commit -m "$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")"
          git push -f "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" sing-box
